
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /usr/java ///
/// Thu Jun 29 19:15:31 UTC 2017 ///

/// interface me.starpy.sdk.StarpySDK ///

public protocol StarpySDK: JavaProtocol {

}

open class StarpySDKForward: JNIObjectForward, StarpySDK {

    private static var StarpySDKJNIClass: jclass?

}


