#if os(Android) 

import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /usr/java ///
/// Thu Jun 29 19:15:31 UTC 2017 ///

/// interface me.starpy.sdk.StarpySDK$Responder ///

public protocol StarpySDK_Responder: JavaProtocol {

    /// public abstract void me.starpy.sdk.StarpySDK$Responder.requestedLogin(java.lang.String)

    func requestedLogin( result: String? )
    func requestedLogin( _ _result: String? )

    /// public abstract void me.starpy.sdk.StarpySDK$Responder.confirmedLogin(java.lang.String)

    func confirmedLogin( result: String? )
    func confirmedLogin( _ _result: String? )

}

open class StarpySDK_ResponderForward: JNIObjectForward, StarpySDK_Responder {

    private static var StarpySDK_ResponderJNIClass: jclass?

    /// public abstract void me.starpy.sdk.StarpySDK$Responder.requestedLogin(java.lang.String)

    private static var requestedLogin_MethodID_3: jmethodID?

    open func requestedLogin( result: String? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: result, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "requestedLogin", methodSig: "(Ljava/lang/String;)V", methodCache: &StarpySDK_ResponderForward.requestedLogin_MethodID_3, args: &__args, locals: &__locals )
    }

    open func requestedLogin( _ _result: String? ) {
        requestedLogin( result: _result )
    }

    /// public abstract void me.starpy.sdk.StarpySDK$Responder.confirmedLogin(java.lang.String)

    private static var confirmedLogin_MethodID_4: jmethodID?

    open func confirmedLogin( result: String? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: result, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "confirmedLogin", methodSig: "(Ljava/lang/String;)V", methodCache: &StarpySDK_ResponderForward.confirmedLogin_MethodID_4, args: &__args, locals: &__locals )
    }

    open func confirmedLogin( _ _result: String? ) {
        confirmedLogin( result: _result )
    }

}

#endif